### ISSUE TITLE
Final Web Client Enhancements

### ISSUE THREAD

**Issue by innovation96** [mssjappjwt/PDSite#11]
@kfitfk final round of bugs and improvements for web client!
Sample talks for testing: 
1. Text Replies - http://localhost:7780/#/talks/571fbfdf0b03a13e00f1cb6b?_k=6v9te1
2. Voice Replies - http://localhost:7780/#/talks/571fbfbf0b03a13e00f1cb69?_k=841n3o
3. Individual Reply Page - http://localhost:7780/#/replies/56d63bbc536e261a00364de3?_k=8vl4rp

**Audio Player Bugs/Improvements**
- [x] Text replies break the fixed global player (play/pause/skip buttons stop working)
- [x] Sub-replies should be part of the auto-play mechanism (currently, the global player skips the sub-reply audio)

**Talk Page Bugs/Improvements**
- [x] If there is sub-reply to a text-only guest post, everything disappears (see this talk for example: http://localhost:7780/#/talks/571fbfdf0b03a13e00f1cb6b?_k=6v9te1) 
- [x] Text replies break fixed global player
- [x] Sub-replies should be part of the auto-play mechanism (currently, the global player skips the sub-reply audio)
- [x] Fix Navbar Logo Hover Zone (can't really click the logo to go to https://getpundit.com)
- [x] Still missing the default profile pic. [See here for example](https://cloud.githubusercontent.com/assets/18356769/14834069/72314616-0bd0-11e6-9b78-3cad7dcec9fe.png). So use /images/guest-profile-pic.png.
- [x] Add timestamps in upper right corner of each post _(format: 1s, 1m, 1h, 1d, 1mo, 1y)_

**Reply Page Bugs**
- [x] Change reply page header text to talk title, not reply text, like this
- [x] Make sure the original reply is shown when the page is for a sub-reply ID, [like this](https://cloud.githubusercontent.com/assets/18356769/14834035/3448bec4-0bd0-11e6-82a3-cd89f1b0e5d3.png).

**Modals**
- [x] Reply modal should transition to download app modal after reply is posted
- [x] Nickname must be all lowercase with no spaces allowed

**Twitter Card**
- [x] Twitter card title should link to talk, reply button should link to reply page
- [x] Render error page for Twitter iFrame (You don't need to style it)

**Comment by kfitfk** [comment]
I didn't notice there's text only reply before. Currently I assume all replies contains audio, which results in uncaught errors for text only replies.

Could you help confirm this bug: 
Does global player always skip sub replies? Or only when there're text only replies?

**Comment by innovation96** [comment]
The global player always skips subreplies no matter what. 

And sorry about the confusion, we just implemented the text reply posting feature! 

The text replies are for guests only - not for regular pundit users. Make sure the global player and play-pause buttons in each reply work when there are text replies present. Right now they don't.

Hope this clears things up! Do you use slack? I can add you to your team channel for faster communication. 

- Chris Aston

**Comment by innovation96** [comment]
Hey! Any updates these couple of days?

**Comment by kfitfk** [comment]
Sorry, I've been busy with my own job this week. I shall work on this issue starting next Tuesday. I'll update the easy ones first. On May 7th, when I'm off work, I'll work on the more complex features like the sound wave interactions and player fixes.

**Comment by innovation96** [comment]
Ok great! Thanks :) 

- Chris Aston

**Comment by kfitfk** [comment]
The height of sound wave is determined by the actual volume of the audio file. I'm not sure how I should adjust the min height.

**Comment by kfitfk** [comment]
Looks like hovering on sound waves to indicate scrubbing state is difficult to implement. I have to read and update the code of the 3rd party library or write a sound wave rendering utility from scratch. For now I make click to seek work.

**Comment by innovation96** [comment]
@kfitfk I removed the soundwave fixes from the list for now. 

- [ ] Add points API. The points are still dummy data in the header of each talk. You can get the API info from @mssjappjwt. 

- [ ] Add talk participants API. You can also get this API info from @mssjappjwt. 

- [ ] Topic has a weird line break. Make sure it's on the same line as the username. Screenshot [here](https://cloud.githubusercontent.com/assets/18356769/15094661/53449efe-1479-11e6-8436-0eea2fb8ed21.png).

**Comment by kfitfk** [comment]
- Missing profile pictures. I don't get it. The users in the linked page all have avatars;
- Render uploaded images for talks and replies. Please provide an id which contains uploaded images. An image will help me better style this;
- Make talk and reply pages responsive for mobile. Does the mobile page use a different markup?

- Dimensions of Twitter card are off. Card size changed? I was told it was 500x500. The actual size is larger, right?

**Comment by innovation96** [comment]
_@kfitfk here's some clarification:_

- Render uploaded images for talks and replies. Please provide an id which contains uploaded images. An image will help me better style this
**Here's a talk ID with an image as the first post: 57640ac03f24f21a00bfbcff**
**Here's a talk ID with images in the replies: 5747ad34ff3af31a00c66834**

None of the images render in the web client yet, only the app. Make sure @mssjappjwt provides you with the right routes etc.

- Make talk and reply pages responsive for mobile. Does the mobile page use a different markup?
**There is no separate markup for mobile right now. We need to reduce the width of the reply cards when the window goes below 768px width**

- Dimensions of Twitter card are off. Card size changed? I was told it was 500x500. The actual size is larger, right?
**I measured it and it looks like the card is supposed to be closer to 508x508**

**Comment by kfitfk** [comment]
`talk.participants` is an array of user ids. @mssjappjwt How do I fetch a bunch of user avatars in a single request?

**Comment by kfitfk** [comment]
For now I redirect to the error page if id is invalid. It is possible to catch all JS errors. It's better to let unknown errors thrown than redirecting in every case.

**Comment by kfitfk** [comment]
The recipient of reply on Twitter card is not part of the twitter_embed.html page. Is something wrong with the ID setup?

**Comment by innovation96** [comment]
@kfitfk 

- [ ] Can we style the pictures a bit better? Make them fill the width of the row (with 10px padding on the left and right) and go below the text.

- [ ] Account for the default profile pic in the participants row, if there is no profile pic. [Screenshot here](https://cloud.githubusercontent.com/assets/18356769/16280412/5910aa3e-388d-11e6-8d1a-74f69b2fdbba.png).

**Comment by kfitfk** [comment]
@innovation96 

Images now fills the width of the row. I don't have an id to test if default profile picture for participants works. I've added the code anyway.

As for the mobile page, some CSS media query should work for the width of reply cards. However, updating the sound waves to fit the width on browser viewport size change requires extra work, which brings us back to the third party soundwave library issue. One specific case of viewport size change on a mobile device is device orientation changing.

**Comment by innovation96** [comment]
Here's the mobile version for the Pundit web client: 
1. Original Post with audio [https://cloud.githubusercontent.com/assets/18356769/16534156/a0e6b16c-3fab-11e6-878a-0250f62b8df2.png](url)

2. Replies below the fold [https://cloud.githubusercontent.com/assets/18356769/16534164/aefb0816-3fab-11e6-85e9-911bec950eb7.png](url)

3. Reply modal, no user input [https://cloud.githubusercontent.com/assets/18356769/16534168/ba491f46-3fab-11e6-9331-34b0a220cfc6.png](url)

4. Reply modal, with user input [https://cloud.githubusercontent.com/assets/18356769/16534171/c2ce7d8c-3fab-11e6-976e-86bec04e15a6.png](url)

5. 'Get App' modal, appears after user posts reply [https://cloud.githubusercontent.com/assets/18356769/16534176/cded24a2-3fab-11e6-8ee3-e8898fe97116.png](url)

6. Error message if reply posting fails [https://cloud.githubusercontent.com/assets/18356769/16534186/e4a0cfc8-3fab-11e6-8368-6aed9807b36a.png](url)

- The window should have lazy scrolling, so the browser bars should be locked. 
- The background color should be based on a color API that @mssjappjwt will provide.
- The top "Get App" bar should be locked
- Remove the universal player

**Comment by billyshaw** [comment]
Hey guys I think after all these we really need to focus on responsive
mobile web. At least like similar to iPhone kind of design

This should be done by Jim's AMA which is in 3 weeks and plenty of time.

If he spreads it to HRC that would be wonderful.

What do you think?


On Saturday, July 2, 2016, Chris Aston <notifications@github.com> wrote:

> Here's the mobile version for the Pundit web client:
> 1. Original Post with audio
> https://cloud.githubusercontent.com/assets/18356769/16534156/a0e6b16c-3fab-11e6-878a-0250f62b8df2.png
> <http://url>
>
>    1.
>
>    Replies below the fold
>    https://cloud.githubusercontent.com/assets/18356769/16534164/aefb0816-3fab-11e6-85e9-911bec950eb7.png
>    <http://url>
>    2.
>
>    Reply modal, no user input
>    https://cloud.githubusercontent.com/assets/18356769/16534168/ba491f46-3fab-11e6-9331-34b0a220cfc6.png
>    <http://url>
>    3.
>
>    Reply modal, with user input
>    https://cloud.githubusercontent.com/assets/18356769/16534171/c2ce7d8c-3fab-11e6-976e-86bec04e15a6.png
>    <http://url>
>    4.
>
>    'Get App' modal, appears after user posts reply
>    https://cloud.githubusercontent.com/assets/18356769/16534176/cded24a2-3fab-11e6-8ee3-e8898fe97116.png
>    <http://url>
>    5.
>
>    Error message if reply posting fails
>    https://cloud.githubusercontent.com/assets/18356769/16534186/e4a0cfc8-3fab-11e6-8368-6aed9807b36a.png
>    <http://url>
>
>
>    - The window should have lazy scrolling, so the browser bars should be
>    locked.
>    - The background color should be based on a color API that @mssjappjwt
>    <https://github.com/mssjappjwt> will provide.
>    - The top "Get App" bar should be locked
>    - Remove the universal player
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mssjappjwt/PDSite/issues/11#issuecomment-230044510>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHwthzT7KALpcVXQ3S34HZPGaV8t17eTks5qRX2dgaJpZM4IQWvV>
> .
>


-- 



*BILLY SHAW SUSANTO *| *Co-Founder & CEO*
*billy@getpundit.com* <billy@getpundit.com>
*+1 917.855.0280*
