### ISSUE TITLE
Pre-launch Web Enhancements

### ISSUE THREAD

**Issue by innovation96** [mssjappjwt/PDSite#15]
**LAST MINUTE IMPROVEMENTS** 

**Web Client:**
- [x] Add topic color UI to talk (play button, nav bar background color)
- [x] Redirect to error page if talk is deleted (i.e., if the talk ID is invalid)
- [x] Max participants visible should be 7. Then, say "+N" for remaining # of participants after the 7th profile picture.
- [x] IF user clicks Like or Sub-reply buttons --> download app modal header text should say "Heads up! Get the Pundit app to join this talk!"
- [x] IF user posts text reply --> download app modal header text should say "Posted! Get the Pundit app to join more talks like this!" 
- [x] Add points icon next to point count. Asset [here](https://cloud.githubusercontent.com/assets/18356769/18024775/ceb303e6-6be0-11e6-9672-3ac94de264a0.png). 

**Embeddable Player:**
We are adding the ability for users to embed a reply or Pundit talk into a website in the form of an iFrame (or something else if you have a better solution).

The embeddable player should have the same functionalities as the Twitter player: 
Width: 500px | Height: 275px
_Functionalities_
- [x] Play audio
- [x] Seek audio
- [x] Listen to full talk button
- [x] Profile picture, username --> topic
- [x] Point count (if it's a talk). Leave that area empty if it's a reply.
- [x] Blurred background profile picture with 0.4 alpha black overlay, 5px rounded border radius

- Full screenshot example [here](https://cloud.githubusercontent.com/assets/18356769/18024787/2cdb888a-6be1-11e6-8ddc-e9887162e91e.png)
- [Talk Example ](https://cloud.githubusercontent.com/assets/18356769/18024790/4247724c-6be1-11e6-9a54-ef5d428a4c5c.png)
- [Reply Example](https://cloud.githubusercontent.com/assets/18356769/18024791/4dfe5740-6be1-11e6-8410-2bf586d0d022.png)

**Embeddable Player ASSETS** (all assets are exported at 2x for retina screen optimization)
- 14x20px [Points icon](https://cloud.githubusercontent.com/assets/18356769/18024792/593cd082-6be1-11e6-8830-8daab773e5ae.png)
- 76x26px [Pundit logo](https://cloud.githubusercontent.com/assets/18356769/18024799/6e4e8844-6be1-11e6-8e15-a200ac6778b3.png)
- 25x36px [Play button](https://cloud.githubusercontent.com/assets/18356769/18024801/757116dc-6be1-11e6-841f-c12ca2e58a1d.png)
- 27x37px [Pause Button](https://cloud.githubusercontent.com/assets/18356769/18024804/88657076-6be1-11e6-97b9-b6ba47c9a558.png)

**Comment by kfitfk** [comment]
Please provide latest available ids of talks and replies (with/without sound).

**Comment by innovation96** [comment]
@kfitfk here you go:

Voice Reply ID: 57beb01a2e816c1a00211d12
Talk ID w/ text and voice replies: 57c0849893cb151a00ba47ea

**Comment by kfitfk** [comment]
Done with the embeddable player page. Use `/generic_embed.html?talk= 57c0849893cb151a00ba47ea` and `/generic_embed.html?reply= 57beb01a2e816c1a00211d12` to preview. It should work the same way as the Twitter embed page.

One thing that I leave out is the talk user name in the reply page. Populating talk only returns the user id, and the `/users` API returns unauthorized when I try to get user info from `http://localhost` using XHR. I've done most of the styles. Please tweak the UI as needed.

**Comment by kfitfk** [comment]
As for the color, should the fixed player use dynamic color? How about the "more replies" button, "send me the app" button and the "Replay to username" button on talk page? On the PC, we have hover state.
Does dynamic color only apply to talk page, or reply page as well?

**Comment by billyshaw** [comment]
Sending several edits to the embeddable player design, thanks :)

**Comment by billyshaw** [comment]
Also, about the username of user in talk. Can you try calling with a query.

so GET /talks/:id?populate=creator.username should do it.

**Comment by innovation96** [comment]
@kfitfk - The following objects should be color coded:

1. Nav bar
2. "Reply to [username] button" on hover state only
3. Play buttons for each reply
4. "Send" button for text reply

That's all!

**Comment by innovation96** [comment]
@kfitfk MODIFICATIONS TO EMBEDDABLE PLAYER

[Updated Embedded Talk Design Here.](https://cloud.githubusercontent.com/assets/18356769/18064830/231ba08a-6dff-11e6-915c-a6facc9dd37f.png)
**Dimensions: 500x500px**

- [ ] If it's a talk, display scrollable replies beneath. You do not need to render sub-replies.
- [ ] Reply profile pics are 30x30px
- [ ] Reply play buttons are 30x30px
- [ ] If the original post has a photo, put it to the left of the caption at 40x40px
- [ ] If the reply has a photo, put it to the right of the caption at 40x40px
- [ ] If the reply has no caption, center it with respect to the profile picture
- [ ] Color code the following buttons with the topic color: Play, Listen on Pundit, Line to the left of each reply
- [ ] There is a black overlay that only covers half the background. Make sure it covers the whole thing.
- [ ] Add a line that goes through the middle of the soundwaves

**Comment by kfitfk** [comment]
Done with the 500x500 embeddable player. Please test it with talk:
1. which contains a picture;
2. which doesn't contain pictures;
3. whose replies contain text replies;
4. whose replies contain pictures.

**Comment by innovation96** [comment]
@kfitfk thanks for the update! :) 

I don't see the replies render though: https://cloud.githubusercontent.com/assets/18356769/18285460/772927c2-743c-11e6-802b-3cc4b4c066fd.png

Can you look into this?

**Comment by kfitfk** [comment]
Ah, guest replies don't have `reply.creator`, should use `reply.nickname`. Fixed.
BTW, please paste the talk like 57c0849893cb151a00ba47ea so I can easily copy it :)
One more problem is that some audio addresses of the replies from this talk is invalid, which will cause a runtime error. I guess it's better to make sure all audios returned from server valid.

**Comment by mssjappjwt** [comment]
![web 1280 13](https://cloud.githubusercontent.com/assets/2715403/18407313/95774eb6-76c1-11e6-96a7-d302b32a1b59.png)
![web 1280 14](https://cloud.githubusercontent.com/assets/2715403/18407314/95775442-76c1-11e6-82b9-4edfee09132b.png)
![web 1280 15](https://cloud.githubusercontent.com/assets/2715403/18407315/9577738c-76c1-11e6-8096-23e2268f8eab.png)
![web 1280 16](https://cloud.githubusercontent.com/assets/2715403/18407312/955897dc-76c1-11e6-85ea-b04f64f5545b.png)

**Comment by mssjappjwt** [comment]
<iframe width="100%" height="500px" scrolling="no" frameborder="no" src="https://getpundit.com/talks/57c0849893cb151a00ba47ea/embed"></iframe>

**Comment by kfitfk** [comment]
The embed buttons have been added now.
One thing to note is that I hard coded the iframe `src` property using domain `https://getpundit.com` because the localhost test server is not configured to support browserHistory.
Modify these two file if needed.
https://github.com/mssjappjwt/PDSite/blob/develop/src/js/components/modals/embedReply.js#L28
https://github.com/mssjappjwt/PDSite/blob/develop/src/js/components/modals/embedTalk.js#L28
