### ISSUE TITLE
New Pages

### ISSUE THREAD

**Issue by mssjappjwt** [mssjappjwt/PDSite#7]
**Below are specs for 2 additional types web client pages: 1) Twitter player iFrame 2) individual reply or sub-reply page linked to reply_id**

**Type I: Single Reply page**
Users will navigate to this type of page when clicking links to individual replies from Twitter, FB, etc  (e.g., https://getpundit.com/replies/id)

> Design here:

![SingleReplyPage](https://cloud.githubusercontent.com/assets/2715403/14733847/0d4ec7ae-0834-11e6-974b-eec12c13dfa1.png)

**Visual Elements**
- [x] Universal Navbar

- [x] Header background: user profile picture, blurred

- [ ] Header details: original talk poster ’username’ —> ‘topic’

- [x] Body: Display only the reply associated with the reply id in the route

- [ ] Include uploaded photo if applicable

- [x] Like/Subreply buttons —> toggle download modal

- [x] ‘Hear Full Talk’ button —> goes to the full talk (e.g., https://getpundit.com/talks/talk_id)

- [x] Fixed Player

**Configure this Route**

- [x] https://getpunditcom/replies/reply_id

**===**

**Twitter Card Spec - focus ONLY on whatever’s in the square frame.
This is an iFrame that will be embedded in Twitter when users share replies, sub-replies, or talks from the Pundit app.**

> Design here:

![twitterplayercard 2x copy](https://cloud.githubusercontent.com/assets/2715403/14733897/6da93936-0834-11e6-9424-a9928c0d4e87.png)

**Visual Elements**

- [x] iFrame Aspect Ratio: Square (500x500)

- [x] Background: Profile Image of poster, blurred 15px with 0.4 Black hue overlay

- [x] Pundit logo, upper right corner (links to https://getpundit.com)

- [x] ‘Username’ —> ‘Topic’

- [x] ‘Play’ button centered in frame

- [x] ‘Reply to [username]’ button —> go to individual reply/sub-reply page

- [x] Render sound waves, bottom aligned

**Configure these Routes**

- [x] getpundit.com/talks/:id/player/

- [x] getpundit.com/replies/:id/player/

**Comment by mssjappjwt** [comment]
**Sample JSON:**

Talk - https://api.getpundit.com/talks/56d63a43536e261a00364dde
Reply - https://api.getpundit.com/replies/56d63bbc536e261a00364de3

**Comment by kfitfk** [comment]
Reply page:

**Header details: original talk poster ’username’ —> ‘topic’**
I don't know how to get channel info from reply. So topic part is not shown now.

**Include uploaded photo if applicable**
Reply page uses the same components from talk page. I'm not sure how to do this.

**‘Hear Full Talk’ button —> goes to the full talk**
I don't find the button in the image. To implement this, if the page is not fully rerendered, there's a lot of modifications with the fixed player due to the playlist syncing problem.

**Comment by mssjappjwt** [comment]
Here is the design with the 'Hear The Full Talk' button:

![singlereplypage 2x](https://cloud.githubusercontent.com/assets/2715403/14759954/6715e81a-0903-11e6-85fc-7c02baf50723.png)

**Comment by kfitfk** [comment]
I pushed a new branch named twitter-embed-page for the Twitter player iframe. To view the page, use:
http://localhost:7780/twitter_embed.html?talk=56cf3fc2b655891a00dbfc4b
http://localhost:7780/twitter_embed.html?reply=56d63bbc536e261a00364de3

The topic and points of reply are not rendered.
I only wrote some basic styles. Please refine as you need.

This is a standalone page. I think it should be as lightweight as possible. So libraries like jQuery and ReactJS are not used. Routes configuration on the backend is required. I use query string to tell whether its talk or reply. If you want to use 2 separate routes, you may need to update the js file as well.

**Comment by innovation96** [comment]
This is what I'm seeing right now:

<img width="516" alt="screen shot 2016-04-23 at 1 16 18 pm" src="https://cloud.githubusercontent.com/assets/18356769/14762962/9bda3072-0955-11e6-9e74-0961fa445d8a.png">

Did you hide all the elements inside the container?

**Comment by mssjappjwt** [comment]
Put in meta data to corresponding page:

> This is the sample data for talk

```
<meta name="twitter:card" content="player" />
<meta name="twitter:site" content="@getpundit" />
<meta name="twitter:title" content={talk.user.name + '\'s Pundit Talk on ' + talk.channels[0].name} />
<meta name="twitter:description" content={talk.title} />
<meta name="twitter:image" content="https://getpundit.com/images/pundit-bar-med.png" />
<meta name="twitter:player:width" content="500" />
<meta name="twitter:player:height" content="500" />
<meta name="twitter:player" content={'https://getpundit.com/' + talk._id + '/player'} />
<meta name="twitter:player:stream:content_type" content="audio/mp4" />
<meta name="twitter:player:stream" content={talk.audio.url} />
```

> This is the sample data for reply

```
<meta name="twitter:card" content="player" />
<meta name="twitter:site" content="@getpundit" />
<meta name="twitter:title" content={reply.text} />
<meta name="twitter:image" content="https://getpundit.com/images/pundit-bar-med.png" />
<meta name="twitter:player:width" content="500" />
<meta name="twitter:player:height" content="500" />
<meta name="twitter:player" content={'https://getpundit.com/' + reply._id + '/player'} />
<meta name="twitter:player:stream:content_type" content="audio/mp4" />
<meta name="twitter:player:stream" content={reply.answer.aws.url} />
```

**Comment by mssjappjwt** [comment]
Use v0.0.2 branch for further dev

**Comment by kfitfk** [comment]
Well, I think it's better to render the whole page at the back end. The `<meta>` info in `<head>` requires details about the talk/reply. When writing these info using JavaScript, the page has been loaded and `<head>`'s been parsed.

**Comment by billyshaw** [comment]
@kfitfk I will do it in the back end thanks!
